services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - "25565:25565"  # Minecraft server port
      - "24454:24454/udp"  # Simple Voice Chat port
    environment:
      EULA: "TRUE"
      TYPE: "FABRIC"
      VERSION: "LATEST"
      MEMORY: "10G"
      MOTD: "\\u00A7b\\u00A7lDionysos MC Server \\u00A7r\\u00A78- \\u00A7fWelcome!"
      # Enable optimizations
      USE_AIKAR_FLAGS: "true"
      # Server configuration
      DIFFICULTY: "normal"
      MAX_PLAYERS: "20"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      ENABLE_COMMAND_BLOCK: "true"
      FORCE_GAMEMODE: "false"
      GENERATE_STRUCTURES: "true"
      HARDCORE: "false"
      PVP: "true"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      PLUGINS_FILE: "/extras/plugins.txt"
      MODS_FILE: "/extras/mods.txt"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./srv/minecraft-data:/data
      - ./plugins.txt:/extras/plugins.txt:ro
      - ./mods.txt:/extras/mods.txt:ro
    networks:
      - minecraft
  
  mc-backup:
    image: itzg/mc-backup:latest
    environment:
      BACKUP_INTERVAL: "12h"
      BACKUP_METHOD: "tar"
      INITIAL_DELAY: "2m"
      # Backup retention
      PRUNE_BACKUPS_DAYS: "7"
      # RCON connection to server
      RCON_HOST: "mc"
      RCON_PORT: "25575"
    volumes:
      # mount the same volume used by server, but read-only
      - ./srv/minecraft-data:/data:ro
      # use a host attached directory for backups
      - ./srv/mc-backups:/backups
    depends_on:
      - mc
    networks:
      - minecraft
    restart: unless-stopped

networks:
  minecraft:
    driver: bridge
